version: "3.7"
services:
  db:
    hostname: db
    image: postgres:14-alpine
    volumes:
      - pgdata:/pgdata
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - PGDATA=pgdata
    ports:
      - "127.0.0.1:${PGPORT}:5432"

  app:
    container_name: api-rest-app
    hostname: app
    build: .
    volumes:
      - .:/app
      - gomodules:/go/pkg/mod
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=1
    ports:
      - "127.0.0.1:${APP_PORT}:8080"
    depends_on:
      - db

  debug:
    container_name: api-rest-app-debug
    hostname: debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - .:/app
      - gomodules:/go/pkg/mod
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=1
    ports:
      - "127.0.0.1:${APP_PORT}:8080"
      - "127.0.0.1:${APP_DEBUG_PORT}:40000"
    depends_on:
      - db

  test:
    container_name: api-rest-app-test
    build:
      context: .
      target: tester
    image: api-sample-app:test
    working_dir: /app
    volumes:
      - .:/app
      - gomodules:/go/pkg/mod
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=1
    depends_on:
      - db

  migrate:
    image: migrate/migrate:4
    command: -verbose -path=/migrations -database="postgres://@?sslmode=disable" up
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=1
    depends_on:
      - db

  openapi_editor:
    image: swaggerapi/swagger-editor
    volumes:
      - ./cmd/rest/spec/openapi.yaml:/tmp/openapi.yaml
    environment:
      - SWAGGER_FILE=/tmp/openapi.yaml
    ports:
      - "127.0.0.1:18081:8080"

volumes:
  pgdata:
  gomodules: