services:
  db:
    hostname: db
    image: postgres:16-alpine
    volumes:
      - pgdata:/pgdata
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
      - PGDATA=pgdata
    ports:
      - "127.0.0.1:${PGPORT}:5432"

  migrate:
    build:
      context: .
      target: migrations
    image: api-sample-app:migrations
    volumes:
      - ./migrations:/migrations
      - ./testdata/migrations:/testdata/migrations
    env_file:
      - .env
    environment:
      - DOCKER_BUILDKIT=1
      - PGHOST=host.docker.internal
    depends_on:
      - db

  openapi_editor:
    image: swaggerapi/swagger-editor
    volumes:
      - ./cmd/rest/spec/openapi.yaml:/tmp/openapi.yaml
    environment:
      - SWAGGER_FILE=/tmp/openapi.yaml
    ports:
      - "127.0.0.1:18081:8080"

volumes:
  pgdata: